/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas78;

/**
 *
 * @author HYPE AMD
 */
public class Kalkulator extends javax.swing.JFrame {
    String angka = "";
    double jumlah, angka1, angka2;
    int pilih;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulator.class.getName());

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AngkaTF = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        tujuhBT = new javax.swing.JButton();
        delapannBT = new javax.swing.JButton();
        sembilanBT = new javax.swing.JButton();
        empatBT = new javax.swing.JButton();
        limaBT = new javax.swing.JButton();
        enamBT = new javax.swing.JButton();
        satuBT = new javax.swing.JButton();
        duaBT = new javax.swing.JButton();
        tigaBT = new javax.swing.JButton();
        titikBT = new javax.swing.JButton();
        nolBT = new javax.swing.JButton();
        cBT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        plusBT = new javax.swing.JButton();
        minBT = new javax.swing.JButton();
        kaliBT = new javax.swing.JButton();
        bagiBT = new javax.swing.JButton();
        samadenganBT = new javax.swing.JButton();
        persenBT = new javax.swing.JButton();
        bBT = new javax.swing.JButton();
        eBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        AngkaTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(AngkaTF);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        tujuhBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tujuhBT.setText("7");
        tujuhBT.addActionListener(this::tujuhBTActionPerformed);

        delapannBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        delapannBT.setText("8");
        delapannBT.addActionListener(this::delapannBTActionPerformed);

        sembilanBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sembilanBT.setText("9");
        sembilanBT.addActionListener(this::sembilanBTActionPerformed);

        empatBT.setFont(empatBT.getFont().deriveFont((float)24));
        empatBT.setText("4");
        empatBT.addActionListener(this::empatBTActionPerformed);

        limaBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        limaBT.setText("5");
        limaBT.addActionListener(this::limaBTActionPerformed);

        enamBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        enamBT.setText("6");
        enamBT.addActionListener(this::enamBTActionPerformed);

        satuBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        satuBT.setText("1");
        satuBT.addActionListener(this::satuBTActionPerformed);

        duaBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        duaBT.setText("2");
        duaBT.addActionListener(this::duaBTActionPerformed);

        tigaBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tigaBT.setText("3");
        tigaBT.addActionListener(this::tigaBTActionPerformed);

        titikBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titikBT.setText(".");
        titikBT.addActionListener(this::titikBTActionPerformed);

        nolBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nolBT.setText("0");
        nolBT.addActionListener(this::nolBTActionPerformed);

        cBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cBT.setText("C");
        cBT.addActionListener(this::cBTActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titikBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(satuBT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(empatBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tujuhBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delapannBT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(limaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(duaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nolBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sembilanBT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(enamBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tigaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tujuhBT, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(delapannBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sembilanBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empatBT, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(limaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enamBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(satuBT, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(duaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tigaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titikBT, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(nolBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        plusBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        plusBT.setText("+");
        plusBT.addActionListener(this::plusBTActionPerformed);

        minBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        minBT.setText("-");
        minBT.addActionListener(this::minBTActionPerformed);

        kaliBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        kaliBT.setText("*");
        kaliBT.addActionListener(this::kaliBTActionPerformed);

        bagiBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bagiBT.setText("/");
        bagiBT.addActionListener(this::bagiBTActionPerformed);

        samadenganBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        samadenganBT.setText("=");
        samadenganBT.addActionListener(this::samadenganBTActionPerformed);

        persenBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        persenBT.setText("%");
        persenBT.addActionListener(this::persenBTActionPerformed);

        bBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bBT.setText("B");
        bBT.addActionListener(this::bBTActionPerformed);

        eBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eBT.setText("E");
        eBT.addActionListener(this::eBTActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bagiBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plusBT, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minBT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(samadenganBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kaliBT, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(persenBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(bBT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eBT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kaliBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plusBT, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bagiBT, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(samadenganBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(persenBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tujuhBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhBTActionPerformed
        angka += "7";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_tujuhBTActionPerformed

    private void delapannBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapannBTActionPerformed
        angka += "8";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_delapannBTActionPerformed

    private void sembilanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanBTActionPerformed
        angka += "9";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_sembilanBTActionPerformed

    private void empatBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatBTActionPerformed
        angka += "4";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_empatBTActionPerformed

    private void limaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaBTActionPerformed
        angka += "5";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_limaBTActionPerformed

    private void enamBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamBTActionPerformed
        angka += "6";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_enamBTActionPerformed

    private void satuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuBTActionPerformed
        angka += "1";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_satuBTActionPerformed

    private void duaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaBTActionPerformed
        angka += "2";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_duaBTActionPerformed

    private void tigaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaBTActionPerformed
        angka += "3";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_tigaBTActionPerformed

    private void nolBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolBTActionPerformed
        angka += "0";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_nolBTActionPerformed

    private void titikBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikBTActionPerformed
        angka += ".";
        AngkaTF.setText(angka);
    }//GEN-LAST:event_titikBTActionPerformed

    private void plusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBTActionPerformed
        angka1 = Double.parseDouble(angka);
        AngkaTF.setText("+");
        angka = "";
        pilih = 1; 

    }//GEN-LAST:event_plusBTActionPerformed

    private void minBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBTActionPerformed
        angka1 = Double.parseDouble(angka);
        AngkaTF.setText("-");
        angka = "";
        pilih = 2; 
    }//GEN-LAST:event_minBTActionPerformed

    private void kaliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliBTActionPerformed
        angka1 = Double.parseDouble(angka);
        AngkaTF.setText("*");
        angka = "";
        pilih = 3; 
    }//GEN-LAST:event_kaliBTActionPerformed

    private void bagiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiBTActionPerformed
        angka1 = Double.parseDouble(angka);
        AngkaTF.setText("/");
        angka = "";
        pilih = 4; 
    }//GEN-LAST:event_bagiBTActionPerformed

    private void persenBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenBTActionPerformed
        angka1 = Double.parseDouble(angka);
        AngkaTF.setText("%");
        angka = "";
        pilih = 5; 
    }//GEN-LAST:event_persenBTActionPerformed

    private void samadenganBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganBTActionPerformed
        if (!angka.isEmpty()) { 
        switch (pilih) {
            case 1:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 + angka2;
                break; // Cukup hitung jumlahnya saja di sini
            case 2:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 - angka2;
                break;
            case 3:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 * angka2;
                break;
            case 4:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 / angka2;
                break;
            case 5:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 % angka2;
                break;
        }
        
        if (jumlah % 1 == 0) {
            angka = String.valueOf((int) jumlah);
        } else {
            angka = String.valueOf(jumlah);
        }
        
        AngkaTF.setText(angka);
    }

    }//GEN-LAST:event_samadenganBTActionPerformed

    private void cBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBTActionPerformed
        AngkaTF.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_cBTActionPerformed

    private void bBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBTActionPerformed
        if (angka.length() > 0) {
            StringBuilder strB = new StringBuilder(angka);
            strB.deleteCharAt(angka.length() - 1);
            angka = strB.toString();
            AngkaTF.setText(angka);
        }
    }//GEN-LAST:event_bBTActionPerformed

    private void eBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_eBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AngkaTF;
    private javax.swing.JButton bBT;
    private javax.swing.JButton bagiBT;
    private javax.swing.JButton cBT;
    private javax.swing.JButton delapannBT;
    private javax.swing.JButton duaBT;
    private javax.swing.JButton eBT;
    private javax.swing.JButton empatBT;
    private javax.swing.JButton enamBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaliBT;
    private javax.swing.JButton limaBT;
    private javax.swing.JButton minBT;
    private javax.swing.JButton nolBT;
    private javax.swing.JButton persenBT;
    private javax.swing.JButton plusBT;
    private javax.swing.JButton samadenganBT;
    private javax.swing.JButton satuBT;
    private javax.swing.JButton sembilanBT;
    private javax.swing.JButton tigaBT;
    private javax.swing.JButton titikBT;
    private javax.swing.JButton tujuhBT;
    // End of variables declaration//GEN-END:variables
}
